---
title: "M11"
author: "Jacqui Unciano"
date: "2023-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```
```{r}
# Exercise 11.2
scores <- 
  tibble(
    name = c("mike", "carol", "greg", "marcia", "peter", "jan", "bobby", "cindy", "alice"),
    school = c("south", "south", "south", "south", "north", "north", "north", "south", "south"),
    teacher = c("johnson", "johnson", "johnson", "johnson",  "smith", "smith", "smith", "perry", "perry"),
    sex = c("male", "female", "male", "female", "male", "female", "male", "female", "female"),
    math_score = c(4, 3, 2, 4, 3, 4, 5, 4, 5),
    reading_score = c(1, 5, 2, 4, 5, 4, 1, 5, 4)
)
tb = tibble(scores)
tb
```
```{r}
# Exercise 11.4
v1 = tb %>%
  slice(1:3)
v1
```

```{r}
tb %>%
  arrange(desc(math_score))
```

```{r}
tb %>%
  arrange(name)
```

```{r}
tb %>%
  arrange(sex)
```

```{r}
tb %>%
  group_by(sex) %>%
  summarize(mean(math_score), median(math_score))
```

```{r}
tb %>%
  arrange(school, teacher, sex, math_score, reading_score)
```

```{r}
tb %>%
  select(name, math_score, reading_score)
```

```{r}
tb %>%
  select(-sex)
```

```{r}
tb %>%
  select(-c(math_score, reading_score))
```

```{r}
tb %>%
  relocate(sex)
```

```{r}
tb %>%
  filter(sex=="male" & school=="south")
```

```{r}
tb %>%
  filter(math_score>mean(math_score))
```

```{r}
tb %>%
  filter(math_score>=4 & reading_score >=3)
```

```{r}
tb %>%
  filter(math_score<=3 | reading_score <=3)
```

```{r}
tb %>%
  filter(substr(name,1,1)=="m")
```

```{r}
tb %>%
  group_by(teacher) %>%
  filter(math_score==5)
```

```{r}
tb %>%
  group_by(sex) %>%
  summarise("mean_score"=mean(math_score)) %>%
  filter(mean_score==4)
```

```{r}
tb = tb %>%
  mutate(math_score = math_score*10,
         reading_score = reading_score*10)
tb
```

```{r}
tb %>% 
  mutate(math_reading_avg = (math_score+reading_score)/2)
```

```{r}

```












